project:
  type: manuscript

manuscript:
  article: index.qmd
bibliography: "references.bib"
format:
  html:
    comments:
      hypothesis: true
  # typst: default

  # (other formats)
  # pdf: default

execute:
  freeze: true